t0 = 0
t_final = 10000
initial_alpha = 1e-8
n_terms_taylor = 1
csv_delimiter = "\t"

[param_finder_props]
d_min = 1.0
g_min = 0.5
mu_min = 0

d_max = 3.0000000002
g_max = 2.50000002
mu_max = 5

g_ini = 1.000000001
d_ini = 2.0000000001
mu_ini = 1.3301409949454641e-06

shift_time = 0

# 0 to skip plotting, > 0 to plot
plot_graphs_matplotlib = 1

[param_finder_props.filters]
# Data filters
alpha_min = 0
alpha_max = 1

[time_offset_finder_proprs]
fit_procedure = "nlsq"
